on:
  pull_request:

jobs:
  check_changelog_fragment:
    runs-on: ubuntu-latest
    env:
      PR_NUMBER: ${{ github.event.pull_request.number }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: pip install towncrier
      - name: Check if a changelog fragment is present
        run: towncrier check
      - name: Make sure exactly one valid Towncrier fragment exists
        shell: bash
        run: |
          set -euo pipefail

          dir="changes"
          pr="$PR_NUMBER"

          # Collect *.md fragments (skip README)
          mapfile -t fragments < <(
              find "$dir" -type f -name '*.md' ! -name 'README.md' -printf '%P\n'
          )

          # 1) Exactly one fragment?
          if [ "${#fragments[@]}" -ne 1 ]; then
              echo "::error::Exactly one changelog fragment is required, found ${#fragments[@]}."
              printf 'Found fragments:\n%s\n' "${fragments[*]}"
              exit 1
          fi

          fragment="${fragments[0]}"

          # 2) Name must be <PR>.<type>.md   (type = any non-dot string);
          # type checks have already been performed by towncrier check
          if [[ "$fragment" =~ ^${pr}\.[^.]+\.md$ ]]; then
              echo "✔ Fragment '${fragment}' is valid."
          else
              echo "::error::Fragment '${fragment}' must be named '${pr}.<type>.md'."
              exit 1
          fi
