on:
  pull_request:

jobs:
  check_changelog_fragment:
    name: Check if a towncrier changelog exists
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: pip install towncrier
      - run: towncrier check
