name: Publish package

on:
  workflow_dispatch:
    inputs:
      version:
        description: New version (as specified in setup.cfg)
        required: true

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - name: Initialisation
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install pypa/build
      run: python -m pip install --user build
    - name: Build wheel and sdist
      run: python -m build --sdist --wheel --outdir dist .
    - name: Publish distribution
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
