name: workflow
on: [push]

jobs:
  workflow:
    runs-on: ubuntu-latest
    steps:
      - name: home
        run: |
          echo $HOME
          ls -la
      - name: checkout
        uses: actions/checkout@v2

      - name: read
        run: ls -la
