name: workflow
on: [push]

jobs:
  workflow:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: home
        run: |
          echo $HOME
          ls -la
      - name: checkout
        uses: actions/checkout@v2

      - name: Set env
        run: echo "TEST=$GITHUB_WORKSPACE/script/hello.sh" >> $GITHUB_ENV
      - name: checkout branch
        run: |
          if git rev-parse --quiet --verify time-dependence; then git checkout time-dependence; fi
      - name: test branch
        run: git branch
      - name: test-env
        run: |
          echo pwd
          echo $GITHUB_WORKSPACE
          echo $TEST
      - name: run hello script
        run:
          bash $TEST
      - name: read
        run: ls -la
